### Recuperar todas las películas
GET http://localhost:3000/movies

### Recuperar todas las películas por un genero
GET http://localhost:3000/movies?genre=Action

### Recuperar una película por ID
GET http://localhost:3000/movies/5d91b9b9-4eaa-11ee-b3d8-88d7f6e23e5f

### Crear una película
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
        "Crime",
        "Drama"
    ]
}

### Actualizar una película
PATCH http://localhost:3000/movies/5d91b9b9-4eaa-11ee-b3d8-88d7f6e23e5f
Content-Type: application/json

{
    "title": "The Godfather 200",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
        "Crime",
        "Drama"
    ],
    "rate": 5
}

### Eliminar una película
DELETE http://localhost:3000/movies/5d91b9b9-4eaa-11ee-b3d8-88d7f6e23e5f